"""Pre-spud Offset Hazard Brief (DWOP pack) - printable HTML, generated from the same
models that drive live alerts (closes the planning -> execution gap)."""
from __future__ import annotations

import datetime as dt

from jinja2 import Environment

from .correlation import Target
from .domain.ontology import FORMATION_BY_CODE, FORMATION_ORDER, HAZARD_BY_CODE, RIBBON_HAZARDS
from .kb import KnowledgeBase
from .risk.evidence import risk_profile
from .risk.mw_window import mw_window
from .risk.recommend import recommend

TEMPLATE = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>Offset Hazard Brief - {{ t.name }}</title>
<style>
:root{--ink:#0f172a;--muted:#475569;--line:#cbd5e1;--bg:#fff;--accent:#0e7490}
body{font:13px/1.45 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:var(--ink);background:var(--bg);margin:0}
.page{max-width:980px;margin:0 auto;padding:28px 32px}
h1{font-size:22px;margin:0 0 4px} h2{font-size:16px;margin:26px 0 8px;border-bottom:2px solid var(--accent);padding-bottom:4px}
.meta{color:var(--muted)} .banner{background:#fef3c7;border:1px solid #f59e0b;padding:6px 10px;border-radius:6px;margin:10px 0;font-size:12px}
table{border-collapse:collapse;width:100%;margin:6px 0} th,td{border:1px solid var(--line);padding:5px 7px;text-align:left;vertical-align:top}
th{background:#f1f5f9;font-weight:600} .num{text-align:right;font-variant-numeric:tabular-nums}
.pill{display:inline-block;padding:1px 7px;border-radius:10px;color:#fff;font-size:11px;font-weight:600}
.hi{background:#b91c1c}.md{background:#d97706}.lo{background:#15803d}
.cite{color:var(--muted);font-size:11px} .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}
.box{border:1px solid var(--line);border-radius:8px;padding:10px 12px}
@media print{.noprint{display:none}.page{padding:0}}
</style></head><body><div class="page">
<div class="noprint" style="text-align:right"><button onclick="window.print()">Print / Save PDF</button></div>
<h1>Offset Hazard Brief &mdash; {{ t.name }}</h1>
<div class="meta">Location {{ '%.5f'|format(t.lat) }} N, {{ '%.5f'|format(t.lon) }} E &middot; Structure: {{ struct }} &middot;
Planned TD {{ '{:,.0f}'.format(t.td_md) }} m MD &middot; Offsets within {{ radius }} km: {{ prof.offsets|length }} &middot; Generated {{ now }}</div>
<div class="banner">Generated by eRTMAC-NWIS from offset-well documents and data. Demo build uses SYNTHETIC data. Every statement links to its source report.</div>

<h2>1. Headline risks (formation-aligned look-ahead zones)</h2>
<table><tr><th>Interval (m MD)</th><th>Formation</th><th>Hazard</th><th>Offset evidence</th><th>Model</th><th>Key offsets</th></tr>
{% for z in zones %}<tr><td class="num">{{ '{:,.0f}'.format(z.md0) }}&ndash;{{ '{:,.0f}'.format(z.md1) }}</td><td>{{ fm(z.formation) }}</td>
<td><span class="pill {{ 'hi' if z.peak>=0.5 else ('md' if z.peak>=0.25 else 'lo') }}">{{ hz(z.hazard) }}</span></td>
<td>{{ z.n_events }} of {{ z.n_exposed }} wells &middot; {{ '%.0f'|format(z.p_offsets*100) }}% (90% CI {{ '%.0f'|format(z.lo*100) }}&ndash;{{ '%.0f'|format(z.hi*100) }}%)</td>
<td>{{ '%.0f'|format(z.p_model*100) }}%</td><td>{% for e in z.evidence[:4] %}{{ e.well_id }} ({{ e.distance_km }} km, {{ e.spud_year }}){% if not loop.last %}, {% endif %}{% endfor %}</td></tr>
{% else %}<tr><td colspan="6">No clustered offset hazards above threshold.</td></tr>{% endfor %}</table>

<h2>2. Predicted formation tops</h2>
<table><tr><th>Formation</th><th class="num">TVD (m)</th><th class="num">MD (m)</th><th class="num">&plusmn;1&sigma; (m)</th><th class="num">Offsets used</th></tr>
{% for c in order if c in prof.tops and prof.tops[c].tvd <= t.td_tvd + 50 %}<tr><td>{{ fm(c) }}</td><td class="num">{{ '{:,.0f}'.format(prof.tops[c].tvd) }}</td>
<td class="num">{{ '{:,.0f}'.format(prof.tops[c].md) }}</td><td class="num">{{ prof.tops[c].sd }}</td><td class="num">{{ prof.tops[c].n }}</td></tr>{% endfor %}</table>

<h2>3. Offset-derived mud-weight window vs plan</h2>
<table><tr><th>Formation</th><th>Planned MW / ECD (ppg)</th><th>Min MW (kick/collapse P10)</th><th>Max ECD (losses)</th><th>Notes</th></tr>
{% for c, f in win.formations.items() %}{% set sec = plan_at(c) %}<tr><td>{{ fm(c) }}</td><td>{% if sec %}{{ sec.mw_ppg }} / {{ sec.ecd_ppg }}{% endif %}</td>
<td>{{ f.window.min_mw or '&ndash;' }}{% if f.kick.kill_mw_max %} <span class="cite">(max kill MW {{ f.kick.kill_mw_max }})</span>{% endif %}</td>
<td>{{ f.window.max_ecd or '&ndash;' }}</td><td class="cite">{{ f.loss.note or '' }}</td></tr>{% endfor %}</table>

<h2>4. Section-by-section hazards &amp; what worked in offsets</h2>
{% for r in recs %}<div class="box" style="margin-bottom:10px"><b>{{ hz(r.hazard) }} &mdash; {{ fm(r.formation) }}</b>
<span class="cite">({{ r.n_events }} offset events, scope: {{ r.scope }})</span>
<table><tr><th>Action</th><th class="num">Cured</th><th class="num">First try</th><th class="num">Median NPT (h)</th><th>Verdict</th></tr>
{% for a in r.actions[:5] %}<tr><td>{{ a.label }}</td><td class="num">{{ a.cured }}/{{ a.attempts }}</td><td class="num">{{ a.first_try }}</td>
<td class="num">{{ a.median_npt_h or '&ndash;' }}</td><td>{{ a.verdict }}</td></tr>{% endfor %}</table>
{% if r.preventive %}<div><b>Preventive:</b> {% for p in r.preventive %}{{ p.text }}{% if not loop.last %}; {% endif %}{% endfor %}</div>{% endif %}
{% for l in r.lessons[:2] %}<div class="cite">Lesson ({{ l.well_id }}): {{ l.text }} &mdash; {{ l.title }}, p.{{ l.page_no }}</div>{% endfor %}
</div>{% endfor %}

<h2>5. Evidence register</h2>
<table><tr><th>#</th><th>Offset event</th><th>Source</th></tr>
{% for e in evidence %}<tr><td>{{ loop.index }}</td><td>{{ e.well_id }}: {{ e.summary }}</td>
<td class="cite">{% if e.citation %}{{ e.citation.title }}, p.{{ e.citation.page_no }} &mdash; &ldquo;{{ e.citation.text }}&rdquo;{% endif %}</td></tr>{% endfor %}</table>

<h2>6. Live-monitoring watch list (armed in NWIS for this well)</h2>
<ul>{% for z in zones %}<li>From {{ '{:,.0f}'.format(z.md0 - 150) }} m MD: look-ahead alert for {{ hz(z.hazard)|lower }} ({{ fm(z.formation) }}); detectors: {{ detectors[z.hazard] }}.</li>{% endfor %}</ul>
</div></body></html>"""

DETECTORS = {"LOSS": "flow-out drop + pit loss trend, ECD vs window", "KICK": "flow-out gain + pit gain, dxc reversal + gas",
             "STUCK": "stuck-pipe risk index (torque, overpull, SPP)", "TIGHT": "overpull on connections",
             "INSTAB": "torque/SPP erratic, cavings reports", "TORQUE": "torque spike / stick-slip",
             "CEMENT": "cement job plan review (lightweight slurry)"}


def hazard_brief(kb: KnowledgeBase, target: Target, radius_km: float = 8.0, model=None) -> str:
    prof = risk_profile(kb, target, radius_km, model=model)
    zones = prof["zones"]
    win = mw_window(kb, target, max(radius_km, 10.0))
    offset_ids = {o["well_id"] for o in prof["offsets"]}
    recs, seen = [], set()
    for z in zones:
        if (z["hazard"], z["formation"]) in seen:
            continue
        seen.add((z["hazard"], z["formation"]))
        recs.append(recommend(kb, z["hazard"], z["formation"], offset_ids))
    evidence = [e for z in zones for e in z["evidence"]][:25]

    def plan_at(code):
        top = prof["tops"].get(code, {}).get("md")
        return target.section_at(top + 5) if top is not None else None

    env = Environment(autoescape=True)
    tpl = env.from_string(TEMPLATE)
    struct = kb.structures.get(target.structure_id or "", {}).get("name", "-")
    return tpl.render(t=target, prof=prof, zones=zones, win=win, recs=recs, evidence=evidence, radius=radius_km,
                      order=FORMATION_ORDER, struct=struct, now=dt.datetime.now().strftime("%Y-%m-%d %H:%M"),
                      fm=lambda c: FORMATION_BY_CODE[c].name if c in FORMATION_BY_CODE else c,
                      hz=lambda h: HAZARD_BY_CODE[h].label if h in HAZARD_BY_CODE else h, plan_at=plan_at,
                      detectors=DETECTORS)
